config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("crew.urls"))
]

crew/urls.py
from django.urls import path
from . import views

app_name = "crew"

urlpatterns = [
    path('', views.index, name="list_employee"),
    path('crew/create/', views.create_employee, name="create_employee"),
    path('crew/edit/<int:id>/', views.edit_employee, name="edit_employee"),
    path('crew/delete/<int:id>/', views.delete_employee, name="delete_employee"),
    path('crew/<int:id>/', views.details, name="details"),
]

crew/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=200)
    mail = models.EmailField()
    phone = models.CharField(max_length=13)
    poste = models.CharField(max_length=200)
    salary = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.name}"

crew/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nom'}),
            'mail' : forms.EmailInput(attrs={'placeholder': 'exemple@email.com'}),
            'phone' : forms.TextInput(attrs={'placeholder': '+261...'}),
            'poste' : forms.TextInput(attrs={'placeholder': 'Assistan de projet'}),
            'salary' : forms.NumberInput(attrs={'placeholder': 'Salaire en dollars'}),
        }

crew/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Employee
from .forms import EmployeeForm


def index(request):
    employees = Employee.objects.all()
    context = {
        "employees" : employees
    }
    return render(request, "crew/list.html", context)


def details(request, id):
    employee = get_object_or_404(Employee, pk=id)
    context = {
        "employee" : employee
    }
    return render(request, "crew/details.html", context)

def create_employee(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("crew:list_employee")
    form = EmployeeForm()
    return render(request, "crew/formulaire.html", {"form": form})

def edit_employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    if request.method == "POST":
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect("crew:details", id=employee.id)
    form = EmployeeForm(instance=employee)
    return render(request, "crew/formulaire.html", {"form": form})

def delete_employee(request, id):
    employee = get_object_or_404(Employee, pk=id)
    employee.delete()
    return redirect("crew:list_employee")

crew/templates/crew/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des employées</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

crew/templates/crew/details.html
{% extends "crew/base.html" %}

{% block content %}
<h1>{{ employee.name }}</h1>
<h2>{{ employee.poste }}</h2>
<p><a href="mailto:{{ employee.mail }}">{{ employee.mail }}</a></p>
<p><a href="tel:{{ employee.phone }}">{{ employee.phone }}</a></p>
<p>{{ employee.salary }} $</p>
<a href="{% url 'crew:list_employee' %}">< Retour</a>
<a href="{% url 'crew:edit_employee' employee.id %}">Modifier</a>
<a href="{% url 'crew:delete_employee' employee.id %}">Supprimer</a>
{% endblock %}

crew/templates/crew/formulaire.html
{% extends "crew/base.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Valider</button>
</form>
<a href="{% url 'crew:list_employee' %}">< Retour</a>
{% endblock %}

crew/templates/crew/list.html
{% extends "crew/base.html" %}

{% block content %}
<h1>Liste des employées</h1>
<a href="{% url 'crew:create_employee' %}">Créer</a>
{% for employee in employees %}
<h2>
    <a href="{% url 'crew:details' employee.id %}" style="text-decoration: none;">
        {{ forloop.counter }} - {{ employee.name }} ({{ employee.poste }})
    </a>
</h2>
<a href="{% url 'crew:edit_employee' employee.id %}">Modifier</a>
<a href="{% url 'crew:delete_employee' employee.id %}">Supprimer</a>
{% endfor %}
{% endblock %}